### ISSUE TITLE
Why doesn't the version checking logic use smart match?

### ISSUE THREAD

**Issue by raiph** [lizmat/Rakudo-Version#1]
Why not just use smart match?:
```
use rakudo v2023.02;     say v2023.03.beta ~~ v2023.02;     # False
use rakudo v2023.02+;    say v2023.03.beta ~~ v2023.02+;    # True
use rakudo v2023.*.beta; say v2023.03.beta ~~ v2023.*.beta; # True
```

That way users don't have to think about `>` vs `>=`, it just does what they'd expect.

**Comment by lizmat** [comment]
I guess the main reason for this, is that this module was created to allow the documentation to say:

     use rakudo v2022.01;

indicating that that feature became available in that release.  And that implies `>=` semantics.

In hindsight we probably should have given `v2022.01+` `>=` instead of `>` semantics with smartmatch.

**Comment by lizmat** [comment]
I've changed the examples to use `~~` instead of `>` and `>=`.  Does that help?

**Comment by patrickbkr** [comment]
> In hindsight we probably should have given `v2022.01+` `>=` instead of `>` semantics with smartmatch.

Given this module is probably not used in the wild yet, can we still rip this out?
For me reading `use rakudo v2022.01+;` and then *not* having that module work with `v2022.01` is highly confusing.

Also I agree with raiph that when reading `use rakudo v2022.01;` I would expect it to require *exactly* that version.

**Comment by lizmat** [comment]
> Given this module is probably not used in the wild yet, can we still rip this out?
> For me reading use rakudo v2022.01+; and then not having that module work with v2022.01 is highly confusing.

I don't think this is an issue with the module?  But with `Version` matching?

**Comment by lizmat** [comment]
I mean, I could make `use raku v2022.01+` match `v2022.01` || `2022.01+`, but that may give weird ideas about version matching in general?

**Comment by patrickbkr** [comment]
> I mean, I could make `use raku v2022.01+` match `v2022.01` || `2022.01+', but that may give weird ideas about version matching in general?

Agreed. Let's not go down that route.

**Comment by lizmat** [comment]
I've just uploaded 0.0.4: this will not allow you to literally specify a version with a `+` or a `*`.  If you want to use version literals of those types, you will have to use the `Callable` interface, which allows you to apply any semantics that you'd like.

So: `use rakudo v2022.12` means "Rakudo 2022.12 or later".  `use rakudo { ... }` means whatever you want it to mean.

@raiph @patrickbkr Have I addresses your worries sufficiently now?

**Comment by patrickbkr** [comment]
Just so I understand this correctly:

    v0.9 ~~ v1.0+   # False
    v1.1 ~~ v1.0+   # True
    v1.0 ~~ v1.0+   # True

Isn't this `>=` semantics?

**Comment by lizmat** [comment]
Intriguing:

But `dd v2023.02 ~~ v2015.02` gives `Bool::False` ?

Do we have a bug in `Version` comparisons?

**Comment by lizmat** [comment]
Yes, but that would mean one would have to specify `use rakudo v2023.02+` if smartmatch semantics where to be used?

The whole idea was to allow an easy way for the documentation to say "Available since this release" and have easy code to go with it.

Otherwise `RakudoPrereq` may be your thing?

**Comment by lizmat** [comment]
Version checking now uses smartmatch in 0.0.5.  Closing.
